import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <h1>Armani Appolon</h1>
          <ul>
            <li><Link href="/posts/first-post">Question 1</Link></li>
            <li><Link href="/posts/second-post">Question 2</Link></li>
            <li><Link href="/posts/third-post">Question 3</Link></li>
            <li><Link href="/posts/fourth-post">Question 4</Link></li>
            <li><Link href="/posts/fifth-post">Question 5</Link></li>
            <li><Link href="/posts/sixth-post">Question 6</Link></li>
            <li><Link href="/posts/seventh-post">Question 7</Link></li>
          </ul>
        </div>
      </main>
    </>
  )
}
